### ISSUE TITLE
Did you resolve this issue?

### ISSUE THREAD

**Issue by tongqii** [iandundas/WidgetIntentNotUpdatingApp#1]
Hello,
I recently encountered the same problem you reported. I have tried a few approaches, but haven't been successful in resolving it.
I wanted to reach out and ask if you were able to find a solution to this problem?

**Comment by iandundas** [comment]
Sorry you also found this issue! 

I opened a TSI and was told to open a Feedback to report a bug. In the meantime I sadly switched to using Realm instead 🥲

**Comment by tongqii** [comment]
Thank you for your reply. I appreciate your response.

I'm sorry to hear that there isn't a satisfactory solution for the SwiftData issue at the moment.
